### ISSUE TITLE
Script to show masternode status

### ISSUE THREAD

**Issue by strophy** [dashevo/dashmate#17]
Dashman provides a `dashman status` function that shows an overview of the masternode health. 
![image](https://user-images.githubusercontent.com/32928115/77278209-9fc51e00-6d23-11ea-8d93-0481b880c63a.png)

I'd like to implement something similar here, can anyone suggest an appropriate design and language to do this? Then I will make an initial attempt.

**Comment by shumkov** [comment]
Yeah, that's a good idea. There is a lot of L1 and L2 status information that we can output. It would be cool to define what exactly we what to print out for the beginning. Maybe we need several status commands? Or just one with overall info + options that provide more details for a specific section.

**Comment by cloudwheels** [comment]
@strophy NodeJS would make sense for language/platform, built as cli tool (but you could potentially add a web interface)

**Comment by strophy** [comment]
Cool, thanks for kicking this off! I really like the way Docker commands are structured, with general information on the first command and more specific information when further options are provided. How about this for an initial set of commands:

```
mn status           ----> status overview and guide to further commands
mn status core      ----> L1 status, similar to dashman output
mn status platform  ----> L2 status, focus on evo services
mn status network   ----> status of P2P and incoming/outgoing connections
mn status ....      ----> more?
```

This could be followed by further helper commands related to adding config info (`mn config xxx`) and possibly even walking the user through creating and using the registration transactions. Thoughts?

**Comment by shumkov** [comment]
Will `mn status network` be core or platform p2p info?

**Comment by strophy** [comment]
I was thinking of it as similar to the network and peers tab of Dash Core, so L1 status. I don't know enough about what is going on at L2 yet to know what could/should be included from there. Maybe things like status of tendermint consensus could be there too? Input from you, other devs or maybe @thephez would be helpful.

**Comment by shumkov** [comment]
Yeah, I think we need both `mn status core network` and `mn status platform network`

**Comment by mangus** [comment]
I would add:
```
mn status network          --> Both core & platform network status
mn status network core     --> Same as "mn status core network"
mn status network platform --> Same as "mn status platform network"
```

**Comment by shumkov** [comment]
@mangus I guess we will have more `mn status core ...` than just `network`.

**Comment by strophy** [comment]
I'd like to keep the length of commands to 1 or 2 words to keep things simple if possible. How much network information will we realistically be displaying for each one? Maybe we could just include network information in `status core` and `status platform` initially and move it out to a separate command `status network` for both later if we feel it is necessary...

**Comment by shumkov** [comment]
@strophy sounds good!

**Comment by strophy** [comment]
I've prepared a list of [suggested output for each command](https://gist.github.com/strophy/886de72727961402dcf47d1ab1446b50), please add your thoughts! In particular I need help with the platform status, since I am not sure what we can/should be tracking there.

**Comment by shumkov** [comment]
I agree with @cloudwheels it's easier to use JavaScript and something like https://github.com/nexe/nexe
or https://github.com/zeit/pkg

**Comment by shumkov** [comment]
@strophy Cool! I will take a look tomorrow.

**Comment by dashameter** [comment]
@strophy was the feature merged and this issue can be closed?

**Comment by strophy** [comment]
Yes, this is done. Thanks!
