### ISSUE TITLE
Sentinel status error on full node

### ISSUE THREAD

**Issue by thephez** [dashevo/dashmate#270]
## Expected Behavior

Sentinel is only required on masternodes so it doesn't need to run on full nodes.

## Current Behavior

Sentinel runs and an error message is displayed for Sentinel status when running as a full node only.

![image](https://user-images.githubusercontent.com/8145677/107519007-b06dc500-6b7d-11eb-9ba8-02a161a7f768.png)

![image](https://user-images.githubusercontent.com/8145677/107518937-99c76e00-6b7d-11eb-81fd-b7884c416825.png)

## Steps to Reproduce (for bugs)

1. Run a testnet full node
2. Run `mn status:core`

## Your Environment

* Version used: v0.18-dev (3a64af1)
* Operating System and version (desktop, server, or mobile): Linux

**Comment by dashameter** [comment]
@thephez is this issue still current in v.20 master?

**Comment by dashameter** [comment]
on v.21 the sentinel status line still throws an error in fullnode mode

**Comment by strophy** [comment]
Should be resolved in #443, @dashameter please feel free to re-open if the issue persists for you

**Comment by SamKirby22** [comment]
@strophy - can we keep this open for now (I don't have/can't find acccess to reopen). We're tracking this fix and have a task for retesting and closing.

**Comment by shumkov** [comment]
Done!

**Comment by dashameter** [comment]
retest passed :+1:

**Comment by dash-maverick** [comment]
Thanks for the confirmation. @SamKirby22 @dashameter feel free to close in that case.

**Comment by SamKirby22** [comment]
Thanks. Closed.
