### ISSUE TITLE
`No such service: drive_tenderdash` when running group:status

### ISSUE THREAD

**Issue by strophy** [dashevo/dashmate#359]
## Expected Behavior
Status command should return status info for seed nodes

## Current Behavior
Node local_seed
    DockerComposeError: Docker Compose error: No such service: drive_tenderdash

## Possible Solution
Look at how the group command calls the status command 

## Steps to Reproduce (for bugs)

1. dashmate setup local
2. dashmate group:start
3. dashmate group:status
4.

## Context

Trying to check if a local node is working

## Your Environment

* Version used: 0.19.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 14.16.1
* Operating System and version (desktop, server, or mobile): Ubuntu 21.04
* Link to your project:

**Comment by dashameter** [comment]
@strophy can you confirm this issue is still current on v.20 master and if not close the issue ?

**Comment by dashameter** [comment]
@shumkov I just retested this and I still get on v.20:

```
dashmate group:status
Node local_seed
    DockerComposeError: Docker Compose error: No such service: 
    drive_tenderdash

```

**Comment by strophy** [comment]
This occurs because the seed node does not run Tenderdash. PR #424 has a fix (unless we intend to add Tenderdash to the seed node)

**Comment by dash-maverick** [comment]
@strophy since the #424 is already merged, is the initial issue solved ?

**Comment by strophy** [comment]
Yes, this is resolved now
