### ISSUE TITLE
`dashmate setup local` is failing with an `invalid IP address` error

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/dashmate#374]
`dashmate setup local` is failing with an `invalid IP address` error:

`dashmate setup local`
```
✔ Set configuration preset
✔ Set the number of nodes
✔ Enable debug logs
✔ Set the core miner interval
✖ (HTTP code 400) unexpected - invalid IP address in add-host: "host-gateway"
◼ Configure Core nodes
◼ Configure Tenderdash nodes
◼ Initialize Platform
◼ Set default config group
```
## Expected Behavior
Setup local succeeds

## Current Behavior
Set local fails

## Steps to Reproduce (for bugs)
```
git clone -b v0.20.0-dev.3 https://github.com/dashevo/dashmate.git && cd dashmate
npm i && npm link
dashmate setup local
```
## Context
Unable to work on local build

## Your Environment

* Version used: v0.20.0-dev.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js v14.4.0
* Operating System and version (desktop, server, or mobile): Ubuntu [studio] 20.04
* Link to your project: N/A

**Comment by dashameter** [comment]
@cloudwheels can you confirm if this issue is still current with v.20 on master branch or close it if it is fixed?

**Comment by cloudwheels** [comment]
Will check asap...

**Comment by thephez** [comment]
FWIW, I'm not having this issue on 0.21-dev

**Comment by strophy** [comment]
Cannot reproduce on `v0.20` or `v0.21-dev`, closing this issue.
