### ISSUE TITLE
Local windows install fails due to manual `tmp` directory path

### ISSUE THREAD

**Issue by ICJR** [dashevo/dashmate#394]
Local windows install fails on my machine. The issue is linked to the manual absolute path '/tmp/' used to write log files.

## Possible Solution

- [pull request](https://github.com/dashevo/dashmate/pull/393)

## Context

- Absolute path causes installer to create '/tmp/' directory outside of dashmate directory. Replaced `/tmp/` path with `os` node package to resolve the issue.

**Comment by strophy** [comment]
Resolved in #393
